services:
  nutrimate-app:
    container_name: spring
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - database
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: nutrimate-db
    ports:
    - "3308:3306"
    restart: unless-stopped