services:
  nutrimate-app:
    container_name: nutrimate-spring
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
    ports:
      - '8080:8080'
    depends_on:
      - database
  database:
    image: mysql
    container_name: nutrimate-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: nutrimate-db
    ports:
    - "3308:3306"
    restart: unless-stopped