services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: nutrimate-db
    ports:
    - "3308:3306"
    restart: unless-stopped